language: android
jdk: oraclejdk8
env:
  global:
    - ABI="default;armeabi-v7a"
    - ANDROID_BUILD_TOOLS=28.0.3
    - ADB_INSTALL_TIMEOUT=5
    - EMULATOR_API_LEVEL=16
    - SYSTEM_IMAGE=/usr/local/android-sdk/system-images/android-16/default/armeabi-v7a/kernel-ranchu
    - ANDROID_SDK_ROOT=/usr/local/android-sdk

branches:
  only:
    - master

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$EMULATOR_API_LEVEL
    #   Android test (screenshot) init
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    #   Android test (screenshot) end

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - chmod +x gradlew
  - chmod +x tools/pipeline_build.sh
  - ./gradlew dependencies || true
  #   Android test (screenshot) init
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;$ANDROID_BUILD_TOOLS" "extras;android;m2repository"
  - export ANDROID_SDK=$ANDROID_SDK_ROOT
  - export PATH=$ANDROID_SDK/emulator:$ANDROID_SDK/tools:$PATH
  - export PATH=$ANDROID_SDK/tools/bin:$PATH

install:
  - sudo -H pip install pillow
  - sudo -H pip install pillowcase

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  #   Android test (screenshot) end

before_script:
  - git lfs pull
  #   Android test (screenshot) init
  - find /usr/local/android-sdk/system-images -type f
  - avdmanager list target
  - avdmanager list device
  - avdmanager list avd
  - echo no | android create avd --force -n test --device 29 -k "system-images;android-$EMULATOR_API_LEVEL;$ABI" -c 500M
  - emulator @test -no-boot-anim -netspeed full -netdelay none -no-snapshot -skin 768x1280 -memory 2048 -kernel $SYSTEM_IMAGE -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  #   Android test (screenshot) end

jobs:
  include:
    - stage: "Lint"
      script: ./gradlew ktlintFormat ktlint
    - stage: "Testes"
      name: "Unit Tests"
      script: ./gradlew clean designsystem:test
    - script: ./gradlew clean connectedAndroidTest
      name: "Integration Tests"
    - stage: Build and Publish
      script: ./tools/pipeline_build.sh